---
# https://molecule.readthedocs.io/en/latest/configuration.html
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: bguerel/${MOLECULE_DISTRO:-rockylinux8}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      instance:
        self_signed_cert_path: "/etc/ssl/localcerts"
        self_signed_organization_name: "BGUEREL Self-signed CA"
        self_signed_expiration_date_in_days: 3650
        self_signed_create_dhparam: no
        self_signed_domain:
          instance:
            - app01.example.local
verifier:
  name: ansible
...
